os:
  - Visual Studio 2015
  - Visual Studio 2017

platform:
  - x64

configuration:
  #- Debug
  - Release

matrix:
  fast_finish: true

build_script:
  - CD
  - cd ..
  - CD
  - git clone https://github.com/HowardHinnant/date
  - cd date
  - git checkout tags/v3.0.1
  - mkdir build && mkdir prefix && cd build
  - cmake -DCMAKE_INSTALL_PREFIX="%cd%\..\prefix" -DBUILD_TZ_LIB=OFF ..
  - cmake --build . --target install
  - cd ..\..
  - cd sqlpp11
  - CD
  - echo %configuration%
  - mkdir build
  - cd build
  - cmake --version
  - cmake .. -DCMAKE_CXX_FLAGS="/EHsc /wd4503" -DCMAKE_PREFIX_PATH="%cd%\..\..\date\prefix"
  - cmake --build . --config %configuration%
  - ctest . --build-config %configuration%
