language: cpp

os:
  - linux

dist: focal
sudo: required

compiler:
  - clang
  - gcc

env:
  - CONFIG=Release
  - CONFIG=Release TESTS_CXX_STD=17
  #- CONFIG=Debug

notifications:
 email:
   on_success: change
   on_failure: always

install:
  - g++ --version

before_script:
   - mkdir build
   - cd build
   - if [[ "$CONFIG" = "Debug" && "$TRAVIS_OS_NAME" = "linux" ]]; then
         cp -r ../scripts/ . &&
         cp -r ../test_scripts/ . &&
         sudo apt-get install python-pyparsing;
     fi
   - if [[ "$CXX" = "g++" && "$CONFIG" = "Debug" && "$TRAVIS_OS_NAME" = "linux" ]]; then export CXXFLAGS="--coverage"; fi
   - cmake .. -DCMAKE_BUILD_TYPE=$CONFIG -DCMAKE_PREFIX_PATH=$PWD/../date $ADD_OPTS

script:
   - cmake --build . --config $CONFIG
   - ctest --output-on-failure

after_script:
  - ../coveralls
